const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

// Theme colors and fonts matching the HTML
const COLORS = {
  primary: "#002b5b",
  secondary: "#555",
  accent: "#f4f7fb",
  border: "#ccc",
  text: "#222",
  tableEven: "#fafafa",
  tableOdd: "#fff",
  blue: "#3498db",
  good: "#27ae60",
  warning: "#f39c12",
  danger: "#e74c3c",
  gray: "#444",
  lightGray: "#f4f7fb",
};
const FONT_FAMILY = "Helvetica";

// --- HEADER ---
function buildHeader(doc) {
  // Company name
  doc
    .font(FONT_FAMILY + "-Bold")
    .fontSize(26)
    .fillColor(COLORS.primary)
    .text("WORKFLOWS ENGINEERING", { align: "center" });
  // Tagline
  doc
    .font(FONT_FAMILY)
    .fontSize(15)
    .fillColor(COLORS.secondary)
    .text("Professional Construction Management Solutions", {
      align: "center",
    });
  doc
    .fontSize(12)
    .fillColor(COLORS.secondary)
    .text("BUILD YOUR DREAMS", { align: "center" });
  // Divider
  doc.moveDown(0.5);
  doc
    .lineWidth(3)
    .strokeColor(COLORS.primary)
    .moveTo(40, doc.y)
    .lineTo(doc.page.width - 40, doc.y)
    .stroke();
  doc.moveDown(1.5);
}

// --- META SECTION ---
function buildMeta(doc, meta) {
  doc.fontSize(13).fillColor(COLORS.gray).font(FONT_FAMILY);
  const metaLines = [
    { label: "Report Title:", value: meta.title },
    { label: "Month:", value: meta.month },
    { label: "Report Generated:", value: meta.generatedDate },
    { label: "Generated By:", value: meta.generatedBy },
    { label: "Document ID:", value: meta.docId },
    { label: "Status:", value: meta.status },
  ];
  metaLines.forEach((line) => {
    doc.text(`${line.label} ${line.value}`, { align: "right" });
  });
  doc.moveDown(1);
}

// --- SECTION HEADER ---
function sectionHeader(doc, text) {
  doc.moveDown(1.2);
  doc
    .font(FONT_FAMILY + "-Bold")
    .fontSize(16)
    .fillColor(COLORS.primary)
    .text(text.toUpperCase());
  doc
    .lineWidth(2)
    .strokeColor(COLORS.primary)
    .moveTo(40, doc.y)
    .lineTo(doc.page.width - 40, doc.y)
    .stroke();
  doc.moveDown(0.5);
}

// --- EXECUTIVE SUMMARY TABLE ---
function buildSummaryTable(doc, summary) {
  const rows = [
    ["Total Employees", summary.totalEmployees],
    ["Total Working Days", summary.totalDays],
    ["Total Present Days", summary.totalPresent],
    ["Total Absent Days", summary.totalAbsent],
    ["Average Attendance", summary.avgAttendance + "%"],
    ["Total OT Hours", summary.totalOTHours + " hours"],
    ["Average OT per Employee", summary.avgOTPerEmployee + " hours"],
  ];
  doc.fontSize(15).font(FONT_FAMILY);
  const startY = doc.y;
  rows.forEach(([label, value], idx) => {
    doc
      .rect(40, doc.y, (doc.page.width - 80) / 2, 22)
      .fillColor(idx % 2 === 0 ? COLORS.accent : COLORS.tableOdd)
      .fill();
    doc
      .rect(
        40 + (doc.page.width - 80) / 2,
        doc.y,
        (doc.page.width - 80) / 2,
        22
      )
      .fillColor(idx % 2 === 0 ? COLORS.accent : COLORS.tableOdd)
      .fill();
    doc
      .fillColor(COLORS.primary)
      .text(label, 48, doc.y + 5, { width: (doc.page.width - 80) / 2 - 16 });
    doc
      .fillColor(COLORS.text)
      .text(value, 48 + (doc.page.width - 80) / 2, doc.y + 5, {
        width: (doc.page.width - 80) / 2 - 16,
      });
    doc.y += 22;
  });
  doc.moveDown(1);
}

// --- DETAILED TABLE ---
function buildDetailedTable(doc, tableData) {
  // Table headers
  const headers = [
    "#",
    "Employee ID",
    "Employee Name",
    "Present",
    "Absent",
    "OT Hours",
    "Attendance %",
    "Performance",
  ];
  const colWidths = [28, 70, 110, 55, 55, 65, 70, 90];
  const startX = 40;
  let y = doc.y + 8;

  // Header row
  doc
    .rect(startX, y, doc.page.width - 80, 24)
    .fillColor(COLORS.accent)
    .fill();
  let x = startX;
  doc
    .font(FONT_FAMILY + "-Bold")
    .fontSize(14)
    .fillColor(COLORS.primary);
  headers.forEach((h, i) => {
    doc.text(h, x + 6, y + 6, { width: colWidths[i] - 12, align: "left" });
    x += colWidths[i];
  });
  y += 24;

  // Data rows
  tableData.forEach((row, idx) => {
    x = startX;
    doc
      .rect(x, y, doc.page.width - 80, 22)
      .fillColor(idx % 2 === 0 ? COLORS.tableEven : COLORS.tableOdd)
      .fill();
    doc.font(FONT_FAMILY).fontSize(13).fillColor(COLORS.text);

    // Attendance calculations
    const total = parseInt(row.present || 0) + parseInt(row.absent || 0) || 1;
    const percentage = ((parseInt(row.present || 0) / total) * 100).toFixed(1);
    const performance =
      percentage >= 95
        ? "Excellent"
        : percentage >= 90
        ? "Very Good"
        : percentage >= 80
        ? "Good"
        : percentage >= 70
        ? "Fair"
        : "Poor";
    const otHours = parseFloat(row.otHours || 0).toFixed(1);

    const rowData = [
      (idx + 1).toString(),
      row.workerId || "N/A",
      row.name || "N/A",
      (row.present || 0).toString(),
      (row.absent || 0).toString(),
      `${otHours}h`,
      `${percentage}%`,
      performance,
    ];

    rowData.forEach((cell, i) => {
      let color = COLORS.text;
      if (i === 5)
        color =
          otHours > 40
            ? COLORS.danger
            : otHours > 20
            ? COLORS.warning
            : COLORS.good;
      if (i === 6 || i === 7)
        color =
          percentage >= 90
            ? COLORS.good
            : percentage >= 80
            ? COLORS.warning
            : COLORS.danger;
      doc
        .fillColor(color)
        .text(cell, x + 6, y + 5, { width: colWidths[i] - 12, align: "left" });
      x += colWidths[i];
    });
    y += 22;
    // Page break if needed
    if (y > doc.page.height - 120) {
      doc.addPage();
      y = 60;
    }
  });
  doc.y = y + 8;
}

// --- PERFORMANCE SUMMARY TABLE ---
function buildPerformanceSummary(doc, tableData) {
  // Attendance performance
  const performanceStats = {
    excellent: 0,
    veryGood: 0,
    good: 0,
    fair: 0,
    poor: 0,
  };
  tableData.forEach((row) => {
    const total = parseInt(row.present || 0) + parseInt(row.absent || 0) || 1;
    const percentage = (parseInt(row.present || 0) / total) * 100;
    if (percentage >= 95) performanceStats.excellent++;
    else if (percentage >= 90) performanceStats.veryGood++;
    else if (percentage >= 80) performanceStats.good++;
    else if (percentage >= 70) performanceStats.fair++;
    else performanceStats.poor++;
  });
  const perfRows = [
    ["Excellent (95%+)", performanceStats.excellent],
    ["Very Good (90–94%)", performanceStats.veryGood],
    ["Good (80–89%)", performanceStats.good],
    ["Fair (70–79%)", performanceStats.fair],
    ["Poor (<70%)", performanceStats.poor],
  ];
  // Table
  doc.fontSize(13).font(FONT_FAMILY);
  let y = doc.y + 8;
  perfRows.forEach(([label, count], idx) => {
    doc
      .rect(40, y, (doc.page.width - 80) / 2, 20)
      .fillColor(idx % 2 === 0 ? COLORS.accent : COLORS.tableOdd)
      .fill();
    doc
      .rect(40 + (doc.page.width - 80) / 2, y, (doc.page.width - 80) / 2, 20)
      .fillColor(idx % 2 === 0 ? COLORS.accent : COLORS.tableOdd)
      .fill();
    doc
      .fillColor(COLORS.primary)
      .text(label, 48, y + 4, { width: (doc.page.width - 80) / 2 - 16 });
    doc
      .fillColor(COLORS.text)
      .text(count, 48 + (doc.page.width - 80) / 2, y + 4, {
        width: (doc.page.width - 80) / 2 - 16,
      });
    y += 20;
  });
  doc.y = y + 8;
}

// --- OVERTIME DISTRIBUTION TABLE ---
function buildOTDistribution(doc, tableData) {
  const otStats = { high: 0, medium: 0, low: 0, none: 0 };
  tableData.forEach((row) => {
    const ot = parseFloat(row.otHours || 0);
    if (ot > 40) otStats.high++;
    else if (ot > 20) otStats.medium++;
    else if (ot > 0) otStats.low++;
    else otStats.none++;
  });
  const otRows = [
    ["High OT (>40h)", otStats.high],
    ["Medium OT (20–40h)", otStats.medium],
    ["Low OT (1–20h)", otStats.low],
    ["No OT (0h)", otStats.none],
  ];
  let y = doc.y + 8;
  otRows.forEach(([label, count], idx) => {
    doc
      .rect(40, y, (doc.page.width - 80) / 2, 20)
      .fillColor(idx % 2 === 0 ? COLORS.accent : COLORS.tableOdd)
      .fill();
    doc
      .rect(40 + (doc.page.width - 80) / 2, y, (doc.page.width - 80) / 2, 20)
      .fillColor(idx % 2 === 0 ? COLORS.accent : COLORS.tableOdd)
      .fill();
    doc
      .fillColor(COLORS.primary)
      .text(label, 48, y + 4, { width: (doc.page.width - 80) / 2 - 16 });
    doc
      .fillColor(COLORS.text)
      .text(count, 48 + (doc.page.width - 80) / 2, y + 4, {
        width: (doc.page.width - 80) / 2 - 16,
      });
    y += 20;
  });
  doc.y = y + 8;
}

// --- SIGNATURE SECTION ---
function buildSignatureSection(doc) {
  doc.moveDown(2);
  doc
    .font(FONT_FAMILY + "-Bold")
    .fontSize(16)
    .fillColor(COLORS.primary)
    .text("Authorization & Approval");
  doc.moveDown(1);

  // Signature blocks
  const blockWidth = (doc.page.width - 120) / 2;
  const startY = doc.y;
  // Project Manager
  doc
    .rect(40, startY, blockWidth, 80)
    .strokeColor(COLORS.border)
    .lineWidth(1)
    .stroke();
  doc
    .font(FONT_FAMILY + "-Bold")
    .fontSize(14)
    .fillColor(COLORS.primary)
    .text("PROJECT MANAGER", 50, startY + 10);
  doc
    .font(FONT_FAMILY)
    .fontSize(12)
    .fillColor(COLORS.text)
    .text("Signature", 50, startY + 32)
    .text("Print Name", 50, startY + 48)
    .text("Date", 50, startY + 64);

  // HR Department
  doc
    .rect(60 + blockWidth, startY, blockWidth, 80)
    .strokeColor(COLORS.border)
    .lineWidth(1)
    .stroke();
  doc
    .font(FONT_FAMILY + "-Bold")
    .fontSize(14)
    .fillColor(COLORS.primary)
    .text("HR DEPARTMENT", 70 + blockWidth, startY + 10);
  doc
    .font(FONT_FAMILY)
    .fontSize(12)
    .fillColor(COLORS.text)
    .text("Signature", 70 + blockWidth, startY + 32)
    .text("Print Name", 70 + blockWidth, startY + 48)
    .text("Date", 70 + blockWidth, startY + 64);

  doc.y = startY + 100;
}

// --- FOOTER ---
function buildFooter(doc) {
  const footerY = doc.page.height - 60;
  doc
    .lineWidth(1)
    .strokeColor(COLORS.border)
    .moveTo(40, footerY)
    .lineTo(doc.page.width - 40, footerY)
    .stroke();
  doc
    .fontSize(12)
    .fillColor(COLORS.secondary)
    .font(FONT_FAMILY)
    .text(
      "WORKFLOWS ENGINEERING | Professional Construction Management Solutions",
      40,
      footerY + 8,
      { align: "center", width: doc.page.width - 80 }
    );
  doc
    .fontSize(12)
    .text(
      "info@workflowsengineering.com | +1 (555) 123-4567 | www.workflowsengineering.com",
      40,
      footerY + 22,
      { align: "center", width: doc.page.width - 80 }
    );
  doc
    .fontSize(10)
    .fillColor(COLORS.gray)
    .text(
      "This is an official document generated automatically. Unauthorized modification is prohibited.",
      40,
      footerY + 36,
      { align: "center", width: doc.page.width - 80 }
    );
}

// --- MAIN REPORT GENERATION ---
async function generateReportFile(topic, tableData, metadata = {}) {
  const doc = new PDFDocument({
    margin: 40,
    size: "A4",
    info: {
      Title: `${topic} - WORKFLOWS ENGINEERING`,
      Author: "WORKFLOWS ENGINEERING",
      Subject: "Professional Attendance Report",
      Creator: "WSPM Report Management System",
      Keywords: "attendance, report, construction, management",
    },
  });

  const fileName = `Professional_Report_${Date.now()}.pdf`;
  const reportsDir = path.join(__dirname, "../reports");
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }
  const filePath = path.join(reportsDir, fileName);
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // HEADER
  buildHeader(doc);

  // META
  buildMeta(doc, {
    title: topic,
    month: metadata.month || "",
    generatedDate: metadata.generatedDate || new Date().toLocaleDateString(),
    generatedBy: metadata.generatedBy || "HR Department",
    docId:
      metadata.docId ||
      `RPT-${new Date().getFullYear()}-ATT-${String(
        new Date().getMonth() + 1
      ).padStart(3, "0")}`,
    status: metadata.status || "Official Document",
  });

  // EXECUTIVE SUMMARY
  sectionHeader(doc, "Executive Summary");
  // Calculate summary
  const totalEmployees = tableData.length;
  const totalPresent = tableData.reduce(
    (sum, row) => sum + parseInt(row.present || 0),
    0
  );
  const totalAbsent = tableData.reduce(
    (sum, row) => sum + parseInt(row.absent || 0),
    0
  );
  const totalOTHours = tableData.reduce(
    (sum, row) => sum + parseFloat(row.otHours || 0),
    0
  );
  const totalDays = tableData.reduce((max, row) => {
    const days = parseInt(row.present || 0) + parseInt(row.absent || 0);
    return days > max ? days : max;
  }, 0);
  const avgAttendance = totalDays
    ? ((totalPresent / (totalEmployees * totalDays)) * 100).toFixed(1)
    : "0.0";
  const avgOTPerEmployee =
    totalEmployees > 0 ? (totalOTHours / totalEmployees).toFixed(1) : "0.0";
  buildSummaryTable(doc, {
    totalEmployees,
    totalDays,
    totalPresent,
    totalAbsent,
    avgAttendance,
    totalOTHours: totalOTHours.toFixed(1),
    avgOTPerEmployee,
  });

  // DETAILED TABLE
  sectionHeader(doc, "Detailed Attendance & Overtime Report");
  buildDetailedTable(doc, tableData);

  // PERFORMANCE SUMMARY
  sectionHeader(doc, "Attendance Performance Summary");
  buildPerformanceSummary(doc, tableData);

  // OVERTIME DISTRIBUTION
  sectionHeader(doc, "Overtime Distribution");
  buildOTDistribution(doc, tableData);

  // SIGNATURE SECTION
  sectionHeader(doc, "Authorization & Approval");
  buildSignatureSection(doc);

  // FOOTER
  buildFooter(doc);

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on("finish", () => resolve(filePath));
    stream.on("error", reject);
  });
}

module.exports = { generateReportFile };
